services:
  tracker.dotnet.auth:
    image: ${DOCKER_REGISTRY-}trackerdotnetauth
    build:
      context: .
      dockerfile: src/Tracker.Dotnet.Auth/Dockerfile
  database:
    image: postgres:17.4-alpine3.21
    ports:
      - "54326:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  database: {}

